[server]
headless = true
enableCORS = false
enableXsrfProtection = true
port = 8501
maxUploadSize = 200
fileWatcherType = "none"

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"
font = "sans serif"

[caching]
ttl = 3600
maxEntries = 100
